Auto code
ezasm-org/EzASM pull request #110
Opened 2023-02-24 22:22 UTC by michaelschuff

This will literally code your entire project for you

2023-02-27 15:00 UTC, WyattRoss commented
Run the linter, then I'll take a look and review this.

2023-02-28 16:41 UTC, WyattRoss requested changes

2023-02-28 16:41 UTC, WyattRoss commented on src/main/java/com/ezasm/gui/editor/Autocomplete.java
> +            while (m.find()) {
Rebuilding the whole list of keywords seems inefficient especially in larger files. Try this library instead?
https://github.com/bobbylight/AutoComplete

2023-03-31 20:44 UTC, michaelschuff commented
Ok added the changes so it's optimized a bit better. Note we still have to recheck the entire document after every press of the delete key because the functions Autocomplete uses that get called are called after the delete and we don't know what was deleted so we have no way of telling if a label was partially deleted and needs to be removed from our keywords list. ATM it doesn't have to recalculate when you just type a key or paste something so thats good at least.

2023-04-07 15:41 UTC, TrevorBrunette approved these changes
LGTM after suggested changes

2023-04-07 15:41 UTC, TrevorBrunette approved these changes

2023-04-07 15:42 UTC, merged