89 save checking
ezasm-org/EzASM pull request #116
Opened 2023-03-01 23:38 UTC by SamiFawcett

Prompts the user to save their file if the changes they made haven't been saved when closing the application window.

2023-03-02 03:08 UTC, WyattRoss requested changes
Other than the code level changes described in other comments, there are a few behavioral changes I'd like:
- If you open the program you're presented with an empty file. I'd like to be able to close the program without being prompted to save an empty file
- Add a cancel button to the save dialog, pressing it should neither save the file nor close the program, but return the user to the editor
- This one is a bit harder to implement, and I understand if you don't, but making it such that modifying the file, then undoing those modifications (either manually, or with \<C-z\>) shouldn't prompt a save dialog

There is also one bug:
When you make a change to the file, then save that file, pressing ctrl+z to undo the last change will erase the contents of the file.

2023-03-02 03:08 UTC, WyattRoss commented on src/main/java/com/ezasm/gui/WindowCloseListener.java
> +                    "Your changes have not been saved.\nWould you like to save them?");
This isn't fully platform independent. Not all platforms use `\n` for newline. To get a system dependent newline character use `System.getProperties("line.separator")`

2023-03-21 14:00 UTC, SamiFawcett commented
I will setup issues for the problems I couldn't solve for this pr.

2023-03-21 17:41 UTC, WyattRoss approved these changes
Send it

2023-03-21 17:41 UTC, merged